// AUTO-GENERATED by scripts/sync-addresses.mjs from
// rwa-outlet-contracts-core/deployments/11155111.json — do not edit by hand.
export const AQUA = "0xa787dd5ef559569b068283d2617e0d8484c08e9b";
export const SWAP_VM = "0xc4d05fc049b819daaf2753d5a0d32402b8a76d47";
export const NAV_ORACLE = "0x49f587a7203c2ce7765cacdd0d5bf912bf52a692";
export const NAV_EXTRUCTION = "0xfd8c2d242e82f7ba28a2a038461c45481ea3849a";
export const COMPLIANCE_NFT = "0x82e0649ec0783985feb4201f126783bd4fc31031";
export const OUTLET_ROUTER = "0x9c352ae4df4853d25f2691c9183c336e0c112289";
export const USDC = "0x062b2f19c852e486b4b913933420957018d1db31";
export const RWA_TBILL = "0x5456e52531085291a35cf0d902ae72d6616b665d";
export const RWA_CREDIT = "0xfbca2b3334138c109d51f5101343de0a35a0edd9";
export const QUEUE_TBILL = "0xbf14ed0b9e2d3a167f9119082440a91c9c810472";
export const QUEUE_CREDIT = "0xb12ee4d7f546c5b6cb3ecc2b770b9b6780354502";
export const VAULT_EXPRESS = "0x4aaab2c212da4d261e5f50f5a97b5d2d3892e204";
export const VAULT_PATIENT = "0x4c299f2ce2d07c77e8280a286241e0a30ead9ae9";
export const RWA_GATE_HOOK = "0x06ae6eeafc42d4ca4158bd3bddc4b14cc54948c0";
export const FAUCET = "0xe78e87d994358d17aaf4653d8398f22c93fb758a";
